### ISSUE TITLE
License

### ISSUE THREAD

**Issue by schnatterer** [LubikR/SynologyUploader#9]
Could you please add a license to your code, such as the MIT license?
Otherwise it's difficult to reuse your code, which I would like to do.

**Comment by LubikR** [comment]
No problem, see LICENSE.txt.

**Comment by schnatterer** [comment]
I reused some your wifi connecting code in [pmcaFilesystemServer](https://github.com/schnatterer/pmcaFilesystemServer).
Thanks for sharing!
